INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Dachsund", 4, 2, 2, 2, 3, "The Dachshund has an energetic, pleasant expression. Each of the three coat varieties has special attributes: the smooth is short and shining, imparting some protection against the elements; the long hair is sleek, sometimes slightly wavy, providing somewhat more protection; the wire has tight, thick, and hard hair with a finer undercoat, providing maximal protection.", "/images/dachsund.jpg", "https://www.petfinder.com/dog-breeds/dachshund/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Doberman Pinscher", 4, 3, 5, 1, 3, "The Doberman is compactly built, muscular and powerful. They combine elegance and strength, speed and endurance. Their carriage is proud and alert, and their gait is free and vigorous. The Doberman coat is short, smooth, and hard, showing off the exceptionally clean-cut lines of this athletic breed.", "/images/doberman.jpg", "https://www.petfinder.com/dog-breeds/doberman-pinscher/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("German Shephard", 3, 4, 5, 2, 3, "The German Shepherd Dog has an outline of smooth curves on a longer than tall body that’s strong, agile, substantial, and an exceptionally outreaching and elastic gait, covering the ground in great strides. The breed’s dense, straight or slightly wavy double coat comprises harsh, close lying medium length hair.", "/images/shephard.jpg", "https://www.petfinder.com/dog-breeds/german-shepherd/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Labrador Retriever", 4, 3, 5, 2, 5, "The Labrador is a moderate dog, not extreme in any way. It is square or slightly longer than tall, of fairly large bone and substance. The breed’s broad head and strong jaws enabled the dog to carry the largest game birds, such as Canada geese. A heavy body and strong legs enable the dog to swim and run powerfully. The coat, which is short, straight, and dense with a soft undercoat, is weatherproof and helps to protect it from icy waters. The Lab is a working retriever and possesses style without over-refinement, and substance without clumsiness.", "/images/lab.jpg", "https://www.petfinder.com/dog-breeds/labrador-retriever/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Beagle", 3, 3, 1, 1, 5, "The Beagle should look like a miniature Foxhound, and is solid for the size. The Beagle’s moderate size enables the ability to follow on foot. Beagles can also be carried, and they can scurry around in thick underbrush. Their close hard coat protects them from underbrush. Their moderate build enables them to nimbly traverse rough terrain. The Beagle’s amiable personality allows this breed to get along with other dogs and to be a wonderful pet. Beagles are noted for their melodious bay. The deep muzzle allows more room for olfactory receptors, aiding the Beagle’s uncanny sense of smell.", "/images/beagle.jpg", "https://www.petfinder.com/dog-breeds/beagle/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Chihuahua", 5, 1, 2, 2, 2, "The Chihuahua is graceful, small, and compact, slightly longer than he is tall. The Chihuahua has a saucy expression and alert, terrier-like attitude. The coat can be smooth, with soft, glossy hair, or long, with soft straight or wavy coats and fringed ears.", "/images/chihuahua.jpg", "https://www.petfinder.com/dog-breeds/chihuahua/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Akita", 3, 3, 3, 2, 3, "This is a large and powerful breed, with much substance and heavy bone, and is slightly longer than tall. The Akita’s build reflects its original job of finding big game in deep snow and rugged terrain. This breed’s double coat consists of a dense undercoat and straight, rough, outer coat standing off from the body, about 2 inches or less in length. Such a combination provides ample insulation from water and weather. The gait is brisk and powerful. The Akita is a versatile dog of large spitz type, able to perform as hiking companion and protector.", "/images/akita.jpg", "https://www.petfinder.com/dog-breeds/akita/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Rhodesian Ridgeback", 3, 3, 3, 1, 3, "Slightly longer than tall, the Rhodesian Ridgeback combines features of speed, power, and endurance. The Rhodesian Ridgeback has an athletic build. Their stride is efficient and long. Their short glossy coat is adapted for living in hot climates. A distinctive feature is the clearly defined ridge, which starts with two identical whorls just behind their shoulders and taper to the prominence of their hipbones.", "/images/rhodesian-ridgeback.jpg", "https://www.petfinder.com/dog-breeds/rhodesian-ridgeback/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("English Bulldog", 1, 1, 2, 2, 5, "The Bulldog’s heavy, thick-set, low-slung body with wide shoulders gives it a low center of gravity. The massive head, of which the circumference should equal at least the height of the dog at the shoulder, gives ample room for muscular attachment for the strong, wide jaws. The limbs are sturdy, the gait loose-jointed, shuffling, and rolling—this is not a breed that needs to run! The coat is fine and glossy.", "/images/english-bulldog.jpg", "https://www.petfinder.com/dog-breeds/bulldog/");