INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Chihuahua", 5, 1, 2, 2, 2, "The Chihuahua is graceful, small, and compact, slightly longer than he is tall. The Chihuahua has a saucy expression and alert, terrier-like attitude. The coat can be smooth, with soft, glossy hair, or long, with soft straight or wavy coats and fringed ears.", "/images/chihuahua.jpg", "https://www.petfinder.com/dog-breeds/chihuahua/");

    INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Akita", 3, 3, 3, 2, 3, "This is a large and powerful breed, with much substance and heavy bone, and is slightly longer than tall. The Akita’s build reflects its original job of finding big game in deep snow and rugged terrain. This breed’s double coat consists of a dense undercoat and straight, rough, outer coat standing off from the body, about 2 inches or less in length. Such a combination provides ample insulation from water and weather. The gait is brisk and powerful. The Akita is a versatile dog of large spitz type, able to perform as hiking companion and protector.", "/images/akita.jpg", "https://www.petfinder.com/dog-breeds/akita/");

      INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Rhodesian Ridgeback", 3, 3, 3, 1, 3, "Slightly longer than tall, the Rhodesian Ridgeback combines features of speed, power, and endurance. The Rhodesian Ridgeback has an athletic build. Their stride is efficient and long. Their short glossy coat is adapted for living in hot climates. A distinctive feature is the clearly defined ridge, which starts with two identical whorls just behind their shoulders and taper to the prominence of their hipbones.", "/images/rhodesian-ridgeback.jpg", "https://www.petfinder.com/dog-breeds/rhodesian-ridgeback/");

       INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("English Bulldog", 1, 1, 2, 2, 5, "The Bulldog’s heavy, thick-set, low-slung body with wide shoulders gives it a low center of gravity. The massive head, of which the circumference should equal at least the height of the dog at the shoulder, gives ample room for muscular attachment for the strong, wide jaws. The limbs are sturdy, the gait loose-jointed, shuffling, and rolling—this is not a breed that needs to run! The coat is fine and glossy.", "/images/english-bulldog.jpg", "https://www.petfinder.com/dog-breeds/bulldog/");