INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Dachsund", 4, 2, 2, 2, 3, "The Dachshund has an energetic, pleasant expression. Each of the three coat varieties has special attributes: the smooth is short and shining, imparting some protection against the elements; the long hair is sleek, sometimes slightly wavy, providing somewhat more protection; the wire has tight, thick, and hard hair with a finer undercoat, providing maximal protection.", "", "https://www.petfinder.com/dog-breeds/dachshund/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Doberman Pinscher", 4, 3, 5, 1, 3, "The Doberman is compactly built, muscular and powerful. They combine elegance and strength, speed and endurance. Their carriage is proud and alert, and their gait is free and vigorous. The Doberman coat is short, smooth, and hard, showing off the exceptionally clean-cut lines of this athletic breed.", "", "https://www.petfinder.com/dog-breeds/doberman-pinscher/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("German Shephard", 3, 4, 5, 2, 3, "The German Shepherd Dog has an outline of smooth curves on a longer than tall body that’s strong, agile, substantial, and an exceptionally outreaching and elastic gait, covering the ground in great strides. The breed’s dense, straight or slightly wavy double coat comprises harsh, close lying medium length hair.", "", "https://www.petfinder.com/dog-breeds/german-shepherd/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Labrador Retriever", 4, 3, 5, 2, 5, "The Labrador is a moderate dog, not extreme in any way. It is square or slightly longer than tall, of fairly large bone and substance. The breed’s broad head and strong jaws enabled the dog to carry the largest game birds, such as Canada geese. A heavy body and strong legs enable the dog to swim and run powerfully. The coat, which is short, straight, and dense with a soft undercoat, is weatherproof and helps to protect it from icy waters. The Lab is a working retriever and possesses style without over-refinement, and substance without clumsiness.", "", "https://www.petfinder.com/dog-breeds/labrador-retriever/");

INSERT INTO Breeds (breed_name, breed_energy, breed_exercise_req, breed_ease_training, breed_grooming_req, breed_affection_level, breed_descript, breed_photo, breed_link)
    VALUES ("Beagle", 3, 3, 1, 1, 5, "The Beagle should look like a miniature Foxhound, and is solid for the size. The Beagle’s moderate size enables the ability to follow on foot. Beagles can also be carried, and they can scurry around in thick underbrush. Their close hard coat protects them from underbrush. Their moderate build enables them to nimbly traverse rough terrain. The Beagle’s amiable personality allows this breed to get along with other dogs and to be a wonderful pet. Beagles are noted for their melodious bay. The deep muzzle allows more room for olfactory receptors, aiding the Beagle’s uncanny sense of smell.", "", "https://www.petfinder.com/dog-breeds/beagle/");
